[package]
name = "ghost-sync"
version = "0.1.0"
edition = "2021"
authors = ["ronakgh97@gmail.com"]
description = "A composable network libray for Game Development."
license = "MIT"
repository = "https:/github.com/ronakgh97/ghost-sync"
homepage = "https:/github.com/ronakgh97/ghost-sync"
documentation = "https:/github.com/ronakgh97/ghost-sync/master/README.md"

[[example]]
name = "ghost-sync-daemon"
path = "examples/daemon.rs"

[dependencies]
tokio = { version = "1.50.0", features = ["full"] }
dashmap = "6.1.0"
anyhow = "1.0.102"
wincode = { version = "0.4.8", features = ["derive", "uuid"] }
uuid = { version = "1.22.0", features = ["v4"] }
bytes = "1.11.1"
colored = "3.1.1"
dotenv = "0.15.0"
chrono = "0.4.44"

[dev-dependencies]
tokio = { version = "1.50.0", features = ["test-util"] }
rand = "0.10.0"